name: Continuous Integration

on:
  pull_request:
    branches: ["main"]

env:
  GO_VERSION: "1.24.3"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Lint
        uses: dominikh/staticcheck-action@v1.3.0
        with:
          version: "2025.1.1"
          install-go: false
      - name: Test
        run: go test -cover -race ./...
