name: Continuous Integration

on:
  pull_request:
    branches: ["main"]

env:
  GO_VERSION: "1.24.5"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Format check
        run: |
          if [ "$(gofmt -l .)" ]; then
            echo "Code is not properly formatted. Run 'go fmt ./...' to fix."
            gofmt -l .
            exit 1
          fi
      - name: Lint
        uses: dominikh/staticcheck-action@v1.4.0
        with:
          version: "2025.1.1"
          install-go: false
      - name: Test
        run: go test -cover -race ./...
